openapi: '3.0.3'
info:
  title: Message State
  description: API to retrieve both current and historical overview of messages that has been delivered through the message delivery API.
  version: '1.0.0'
servers:
  - url: /integration/message-state/1.0.0
paths:
  /health:
    get:
      summary: Health
      description: Retrieve current health status of this API.
      operationId: check-api-health
      parameters:
        - name: Ocp-Apim-Subscription-Key
          in: header
          required: true
          description: Your personal **subscription key**, which can be acquired by subscribing to one of our products and which can be viewed on your profile page.
          schema:
            type : string
      responses:
        '200':
          description: API is available and working fine.
  /messages/{id}:
    get:
      summary: Retrieve message state
      description: Retrieve both the current state and historical overview for the specified message.
      operationId: retrieve-message-state
      parameters:
        - name: Ocp-Apim-Subscription-Key
          in: header
          required: true
          description: Your personal **subscription key**, which can be acquired by subscribing to one of our products and which can be viewed on your profile page.
          schema:
            type : string
        - name: id
          in: path
          required: true
          description: Unique identifier of your **message**, whose state should be returned.
          schema:
            type : string
      responses:
        '200':
          description: Representation of your message, includes current state and historical overview.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpGetResponse'
        '400':
          description: The specified request is invalid. Please check the returned error, verify the request and try again.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpBadRequestResponse'
        '404':
          description: A message with the specified identifier was not found. Please check the identifier and try again.
        '500':
          description: An internal error occured. Try again and if the problem persists, please contact us. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpServerErrorResponse'
components:
  schemas:
    HttpGetResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Message'
    HttpBadRequestResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error occurred while validating input data."
        validation:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
                  example: "Key: 'Message.IntegrationId' Error:Field validation for 'IntegrationId' failed on the 'required' tag"
        traceId:
            type: string
            example: "3456810315743914459"
    HttpServerErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error occurred while creating message. Please try again and if the problem persists, contact us for further assistance."
        traceId:
          type: string
          example: "3456810315743914459"
    Message:
      type: object
      properties:
        messageId:
          type: string
          example: "89179f90-2153-42b8-adf8-5b0c19d44bd5"
        integrationId:
          type: string
          example: "62a34422145ecb62e374e77b"
        batchId:
          type: string
          example: "da56ce62-f993-11ec-927a-fa23cdbd91f1"
        batchIndexNumber:
          type: string
          example: "0"
        entity:
          type: string
          example: "employee"
        payload:
          type: object
          example: {}
        searchParameters:
          type: object
          example: {}
        currentState:
          type: object
          $ref: '#/components/schemas/MessageState'
        history:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/MessageState'
        created:
          type: string
          format: date-time
          description: Date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
          example: "2022-07-01T23:16:36.074Z"
    MessageState:
      type: object
      properties:
        status:
          type: string
          example: "running"
        description:
          type: string
          example: "Starting to proces message"
        additionalInformation:
          type: object
          example: { "key": "value", "nested": { "example": true } }
        changed:
          type: string
          format: date-time
          description: Date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
          example: "2022-07-01T23:16:36.315Z"