openapi: "3.0.3"
info:
  title: Health
  description: Retrieve current health status of this API.
  version: "v1"
servers:
  - url: /v1
tags:
  - name: Public
paths:
  /health:
    get:
      summary: Health
      description: Retrieve current health status of this API.
      operationId: check-api-health
      tags:
        - Health
      parameters:
        - name: Ocp-Apim-Subscription-Key
          in: header
          required: true
          description: Your personal **subscription key**, which can be acquired by subscribing to one of our products and which can be viewed on your profile page.
          schema:
            type: string
      responses:
        "200":
          description: API is available and working fine.
