openapi: '3.0.3'
info:
  title: Message Delivery
  description: API to deliver messages for an integration of your company.
  version: '1.0.0'
servers:
  - url: /integration/message-delivery/1.0.0
paths:
  /message:
    post:
      summary: Create message
      description: Create a new message for the specified integration.
      operationId: create-message
      parameters:
        - name: integrationId
          in: header
          required: true
          description: Unique identifier of your **integration**, where the message should be delivered to.
          schema:
            type : string
        - name: partnerId
          in: header
          required: true
          description: Unique identifier of your Visma Verzuim **partner** scope, into which the message will be integrated.
          schema:
            type : string
        - name: employerId
          in: header
          required: true
          description: Unique identifier of your Visma Verzuim **employer** scope, into which the message will be integrated.
          schema:
            type : string
        - name: bearer
          in: header
          required: true
          description: Authorization bearer of your Visma Verzuim integration user, which will be used to integrate the message into your instance.
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json: {}
          application/xml: {}
      responses:
        '201':
          description: Unique identifier of your message, can be used to trace the state.
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageId:
                    type: string
                    example: "89179f90-2153-42b8-adf8-5b0c19d44bd5"
        '400':
          description: The specified request is invalid. Please check the error message and try again.
        '500':
          description: An internal error occured. Try again and if the problem persists, please contact us.