openapi: '3.0.3'
info:
  title: Message Delivery
  description: API to deliver XML and JSON messages, which will be processed in your Visma Verzuim product by the integration you have purchased.
  version: '1.0.0'
servers:
  - url: /integration/message-delivery/1.0.0
paths:
  /health:
    get:
      summary: Health
      description: Retrieve current health status of this API.
      operationId: check-api-health
      parameters:
        - name: Ocp-Apim-Subscription-Key
          in: header
          required: true
          description: Your personal **subscription key**, which can be acquired by subscribing to one of our products and which can be viewed on your profile page.
          schema:
            type : string
      responses:
        '200':
          description: API is available and working fine.
  /messages:
    post:
      summary: Create message
      description: Create a new message for the specified integration.
      operationId: create-message
      parameters:
        - name: Ocp-Apim-Subscription-Key
          in: header
          required: true
          description: Your personal **subscription key**, which can be acquired by subscribing to one of our products and which can be viewed on your profile page.
          schema:
            type : string
        - name: Content-Type
          in: header
          required: true
          description: Indicates the original media type of the resource. Valid values are 'application/json' and 'application/xml'.
          schema:
            type : string
        - name: integrationId
          in: header
          required: true
          description: Unique identifier of your **integration**, where the message should be delivered to.
          schema:
            type : string
        - name: partnerId
          in: header
          required: true
          description: Unique identifier of your Visma Verzuim **partner** scope, into which the message will be integrated.
          schema:
            type : string
        - name: employerId
          in: header
          required: true
          description: Unique identifier of your Visma Verzuim **employer** scope, into which the message will be integrated.
          schema:
            type : string
        - name: bearer
          in: header
          required: true
          description: Authorization bearer of your Visma Verzuim integration user, which will be used to integrate the message into your Visma Verzuim product.
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json: {}
          application/xml: {}
      responses:
        '201':
          description: Unique identifier of your message, can be used to trace the state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpCreatedResponse'
                    
        '400':
          description: The specified request is invalid. Please check the error message and try again.
        '500':
          description: An internal error occured. Try again and if the problem persists, please contact us.
components:
  schemas:
    HttpCreatedResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        messageId:
          type: string
          example: "89179f90-2153-42b8-adf8-5b0c19d44bd5"