openapi: '3.0.3'
info:
  title: Message Delivery
  description: API to deliver messages for an integration of your company.
  version: '1.0.1'
servers:
  - url: /integration/message-delivery/1.0.1
paths:
  /message:
    post:
      summary: Create Message
      description: Create a new message for the specified integration.
      operationId: create-message
      parameters:
        - name: integrationId
          in: header
          required: true
          description: Unique identifier of your **integration**, where the message should be delivered to.
          schema:
            type : string
        - name: partnerId
          in: header
          required: true
          description: Unique identifier of your Visma Verzuim **partner** scope, into which the message will be integrated.
          schema:
            type : string
        - name: employerId
          in: header
          required: true
          description: Unique identifier of your Visma Verzuim **employer** scope, into which the message will be integrated.
          schema:
            type : string
        - name: bearer
          in: header
          required: true
          description: Authorization bearer of your Visma Verzuim integration user, which will be used to integrate the message into your instance.
          schema:
            type : string
        - name: test
          in: header
          required: false
          description: Test header to check if version 1.0.1 is active
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json: {}
          application/xml: {}
      responses:
        '201':
          description: Unique identifier of your message. Can be used to trace the message state.
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageStateId:
                    type: string